import type { ToolDescriptor } from '../core/types.js';

export const toolRegistry: ToolDescriptor[] = [
	{
		name: 'wcpay_doctor',
		description: 'Run WooPayments CLI diagnostics for the selected profile.',
		command: 'wcpay doctor --json --redact',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true } },
		examples: [ 'wcpay doctor', 'wcpay doctor --json --redact' ],
	},
	{
		name: 'wcpay_get_mode',
		description: 'Read WooPayments mode flags and classify the store as live, test, or dev.',
		command: 'wcpay mode --json',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true } },
		examples: [ 'wcpay mode', 'wcpay mode --json' ],
	},
	{
		name: 'wcpay_get_account_status',
		description: 'Read WooPayments account status for the selected profile.',
		command: 'wcpay account status --json',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true } },
		examples: [ 'wcpay account status' ],
	},
	{
		name: 'wcpay_get_settings',
		description: 'Read WooPayments settings and mode flags.',
		command: 'wcpay settings get --json',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true } },
		examples: [ 'wcpay settings get' ],
	},
	{
		name: 'wcpay_list_transactions',
		description: 'List WooPayments transactions.',
		command: 'wcpay transactions list --json',
		safety: 'read',
		mcp: true,
		inputs: {
			profile: { type: 'string', optional: true },
			page: { type: 'number', optional: true },
			limit: { type: 'number', optional: true },
		},
		examples: [ 'wcpay transactions list --limit 25 --json' ],
	},
	{
		name: 'wcpay_list_deposits',
		description: 'List WooPayments deposits.',
		command: 'wcpay deposits list --json',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true }, page: { type: 'number', optional: true } },
		examples: [ 'wcpay deposits list --json' ],
	},
	{
		name: 'wcpay_get_deposit',
		description: 'Get a WooPayments deposit by ID.',
		command: 'wcpay deposits get <id> --json',
		safety: 'read',
		mcp: true,
		inputs: { id: { type: 'string' }, profile: { type: 'string', optional: true } },
		examples: [ 'wcpay deposits get po_123 --json' ],
	},
	{
		name: 'wcpay_list_disputes',
		description: 'List WooPayments disputes.',
		command: 'wcpay disputes list --json',
		safety: 'read',
		mcp: true,
		inputs: { profile: { type: 'string', optional: true }, page: { type: 'number', optional: true } },
		examples: [ 'wcpay disputes list --json' ],
	},
	{
		name: 'wcpay_get_dispute',
		description: 'Get a WooPayments dispute by ID.',
		command: 'wcpay disputes get <id> --json',
		safety: 'read',
		mcp: true,
		inputs: { id: { type: 'string' }, profile: { type: 'string', optional: true } },
		examples: [ 'wcpay disputes get dp_123 --json' ],
	},
	{
		name: 'wcpay_get_charge',
		description: 'Get a WooPayments charge by ID.',
		command: 'wcpay charges get <id> --json',
		safety: 'read',
		mcp: true,
		inputs: { id: { type: 'string' }, profile: { type: 'string', optional: true } },
		examples: [ 'wcpay charges get ch_123 --json' ],
	},
	{
		name: 'wcpay_api_get',
		description: 'Make an authenticated GET request to a store REST API path.',
		command: 'wcpay api get <path> --json',
		safety: 'read',
		mcp: true,
		inputs: { path: { type: 'string' }, profile: { type: 'string', optional: true } },
		examples: [ 'wcpay api get /wc/v3/payments/accounts --json' ],
	},
	{
		name: 'wcpay_create_refund',
		description: 'Create a refund in WooPayments test/dev mode.',
		command: 'wcpay refunds create --order <id> --amount <minor-units> --yes --json',
		safety: 'test_mode_write',
		mcp: false,
		inputs: {
			order: { type: 'string', optional: true },
			charge: { type: 'string', optional: true },
			amount: { type: 'number' },
			reason: { type: 'string', optional: true },
			confirm: { type: 'boolean' },
			dryRun: { type: 'boolean', optional: true },
		},
		examples: [ 'wcpay refunds create --order 123 --amount 500 --dry-run --json' ],
	},
	{
		name: 'wcpay_create_test_order',
		description: 'Create a WooCommerce test order from an existing product in WooPayments test/dev mode.',
		command: 'wcpay test order create --product <id> --quantity <n> --yes --json',
		safety: 'test_mode_write',
		mcp: false,
		inputs: {
			product: { type: 'string' },
			quantity: { type: 'number', optional: true },
			email: { type: 'string', optional: true },
			confirm: { type: 'boolean' },
			dryRun: { type: 'boolean', optional: true },
		},
		examples: [ 'wcpay test order create --product 123 --quantity 1 --dry-run --json' ],
	},
];

export function getToolRegistry(): ToolDescriptor[] {
	return toolRegistry;
}
